language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk7
  - openjdk7
script: 
  - "sbt -Dlog4j.configuration=file://$TRAVIS_BUILD_DIR/project/travis-log4j.properties ++$TRAVIS_SCALA_VERSION test"
  - "sbt -Dlog4j.configuration=file://$TRAVIS_BUILD_DIR/project/travis-log4j.properties ++$TRAVIS_SCALA_VERSION publish-local"
  - "sbt coveralls"
notifications:
  email:
    - github.10.dmrolfs@xoxy.net

